StatisticsTgBot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TgAdmin.urls')),
    path('mdeditor/', include('mdeditor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TgAdmin/urls.py
from django.urls import path
from TgAdmin import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('chats/', views.ChatView.as_view(), name='chats'),
    path('chat/<int:pk>/delete/', views.ChatDeleteView.as_view(), name='chat_delete'),
    path('chat/<int:pk>/', views.ChatUpdateView.as_view(), name='chat_edit'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout', views.LogoutThenLoginView.as_view(), name='logout'),
    path('users/inaction', views.InactionView.as_view(), name='inaction_users'),
    path('users/agree/', views.ClickYesView.as_view(), name='click_yes_users'),
    path('users/disagree/', views.ClickNoView.as_view(), name='click_no_users'),
    path('users/all_agree/', views.ClickYesTpView.as_view(), name='click_yes_tp_users'),
    path('users/anonymous', views.IsVneView.as_view(), name='anonymous_users'),
    path('update_text/', views.UpdateText.as_view(), name='text_create'),
    path('update_btn_yes/', views.UpdateBtnYes.as_view(), name='btn1_create'),
    path('update_btn_no/', views.UpdateBtnNo.as_view(), name='btn2_create'),
    path('update_mailing/', views.UpdateMailingView.as_view(), name='mailing'),
    path('update_faq/', views.UpdateFaq.as_view(), name='edit_faq'),
    path('search/', views.SearchResultView.as_view(), name='search_result'),
    path('update_id_admin/', views.UpdateIdAdmin.as_view(), name='edit_id_admin'),
]

TgAdmin/models.py
from mdeditor.fields import MDTextField
from solo.models import SingletonModel

from django.db import models
from django.urls import reverse

from TgAdmin.constants import Const


class Chat(models.Model):
    class Meta:
        verbose_name = 'Название чата'
        verbose_name_plural = 'Названия чатов'

    chat_id = models.CharField(
        max_length=255,
        verbose_name='Id группы',
        unique=True
    )
    name = models.CharField(
        max_length=255,
        verbose_name='Название группы'
    )
    url_link = models.CharField(
        max_length=255,
        verbose_name='Ссылка на тп/магазин',
        choices=Const.LINK,
        default='tp',
        help_text='Выбрать ссылку для перехода пользователя, после нажатия'
                  ' на клавишу "согласен"'
    )
    # здесь language нужен для группового чата
    language = models.CharField(
        max_length=2,
        choices=Const.LANGUAGE,
        default='ru',
        verbose_name='Язык'
    )
    url_chat = models.URLField(
        max_length=255,
        verbose_name='Ссылка на чат',
        blank=True,
        null=True,
        help_text='По умолчанию добавляется ссылка чата. Если измените ссылку-приглашение, то'
                  ' здесь необходимо изменить ссылку'
    )

    def __str__(self):
        return f"chat_id: {self.chat_id}; name: {self.name}"

    def get_absolute_url(self):
        return reverse('chat_edit', args=[str(self.id)])


class Users(models.Model):
    class Meta:
        verbose_name = 'Пользователь телеграма'
        verbose_name_plural = 'Пользователи телеграма'
        ordering = ['-date_joined']
        unique_together = [['iduser', 'chat_id']]

    iduser = models.CharField(
        max_length=255,
        verbose_name='ID пользователя',
        db_index=True
    )
    username = models.CharField(
        max_length=255,
        verbose_name='Username пользователя',
        blank=True,
        null=True,
    )
    fullname = models.CharField(
        max_length=255,
        verbose_name='Полное имя пользователя',
        blank=True,
        null=True
    )
    date_joined = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата добавления пользователя'
    )
    state = models.CharField(
        max_length=1,
        choices=Const.STATE,
        default='1',
        db_index=True
    )
    chat_id = models.ForeignKey(
        Chat,
        on_delete=models.SET_NULL,
        null=True,
        related_name='users'
    )
    is_banned = models.BooleanField(default=False)
    # Здесь language нужен для техподдержки
    language = models.CharField(
        max_length=2,
        choices=Const.LANGUAGE_SUPPORT,
        default='no'
    )
    message_id = models.CharField(
        max_length=255,
        verbose_name="Id сообщения при вступлении в группу",
        blank=True,
        null=True
    )

    def __str__(self):
        return f"id-{self.iduser}: username-{self.username}, fullname-{self.fullname}"


def user_directory_path(instance, filename):
    return '{0}'.format(filename)


class Data(SingletonModel):
    class Meta:
        verbose_name = 'Данные для изменения'

    text_before_btn = MDTextField(
        verbose_name='Текст рядом с кнопками (русский)',
        default='Текст для приветствия новых пользователей в чате на русском языке'
    )
    text_before_btn_en = MDTextField(
        verbose_name='Текст рядом с кнопками (english)',
        default='Текст для приветствия новых пользователей в чате на английском языке'
    )
    image = models.ImageField(
        blank=True,
        null=True,
        upload_to=user_directory_path,
        verbose_name='Фотография для текста'
    )
    btn1 = models.CharField(
        max_length=255,
        verbose_name='Кнопка 1 (русский)',
        default='Согласен'
    )
    btn1_en = models.CharField(
        max_length=255,
        verbose_name='Кнопка 1 (english)',
        default='Agree'
    )
    btn2 = models.CharField(
        max_length=255,
        verbose_name='Кнопка 2 (русский)',
        default='Отклонить'
    )
    btn2_en = models.CharField(
        max_length=255,
        verbose_name='Кнопка 2 (english)',
        default='Reject'
    )
    faq = models.TextField(
        verbose_name='FAQ для техподдержки',
        default=Const.TEXT_FOR_FAQ
    )
    faq_en = models.TextField(
        verbose_name='FAQ english для техподдержки',
        default=Const.TEXT_FOR_FAQ_EN
    )
    text_mailing = models.TextField(
        verbose_name='Текс для рассылки в техподдержке',
        default='Текст для рассылки'
    )
    id_admin = models.CharField(
        max_length=100,
        verbose_name='ID пользователя',
        help_text='ID пользователя, кто будет добавлять чаты в БД',
        default='',
    )

    def __str__(self):
        return 'Данные для изменения'


class TempDataSupport(models.Model):
    class Meta:
        verbose_name = 'Временные данные техподдержки'
        verbose_name_plural = 'Временные данные техподдержки'

    id_message = models.CharField(
        max_length=255,
        verbose_name='ID сообщения в техподдержке'
    )
    id_user = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='ID пользователя'
    )
    text = models.TextField(
        verbose_name='Текст сообщения',
        blank=True,
        null=True
    )

    def __str__(self):
        return 'Временные данные техподдержки'


class TempDataBtn(models.Model):
    class Meta:
        verbose_name = 'Временные данные для обработчика'
        verbose_name_plural = 'Временные данные для обработчика'

    id_message = models.CharField(
        max_length=255,
        verbose_name="ID сообщения в техподдержке"
    )
    id_user = models.CharField(
        max_length=255,
        unique=True,
        verbose_name='ID пользователя'
    )

    def __str__(self):
        return 'Временные данные для обработчика'

TgAdmin/views.py
from telebot import TeleBot
from telebot import apihelper

from django.conf import settings
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import reverse
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from TgAdmin import forms
from TgAdmin.models import Users, Data, Chat
from TgAdmin.mixins import ObjectListMixin


class SearchResultView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
    Поиск пользователей
    """
    template_name = "TgAdmin/search.html"
    model = Users

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Users.objects.filter(
            Q(username__icontains=query) |
            Q(fullname__icontains=query) |
            Q(chat_id__name__icontains=query)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_search'] = self.get_queryset().count()
        context['search'] = self.request.GET.get('q')
        return context


class ChatView(LoginRequiredMixin, ListView):
    """
        Список чатов
    """
    template_name = "TgAdmin/chats.html"
    model = Chat


class ChatUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
        Изменение параметров чата
    """
    model = Chat
    template_name = 'TgAdmin/edit_chat.html'
    form_class = forms.ChatForm
    success_message = 'Данные успешно изменены'


class ChatDeleteView(DeleteView):
    """
        Удаление чата
    """
    model = Chat
    template_name = 'TgAdmin/delete_chat.html'
    success_url = reverse_lazy('chats')


class HomeView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список всех пользователей
    """
    template_name = "TgAdmin/home.html"
    model = Users
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_count'] = Users.objects.all().count()
        return context


class InactionView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список пользователей, которые бездействуют
    """
    template_name = "TgAdmin/inaction_users.html"
    model = Users
    paginate_by = 10

    def get_queryset(self):
        return Users.objects.filter(state='1')


class ClickYesView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список пользователей, которые нажали "да" в чате
    """
    template_name = "TgAdmin/click_yes_users.html"
    model = Users
    paginate_by = 10

    def get_queryset(self):
        return Users.objects.filter(state='2')


class ClickNoView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список пользователей, которые нажали "нет" в чате
    """
    template_name = 'TgAdmin/click_no_users.html'
    model = Users
    paginate_by = 10

    def get_queryset(self):
        return Users.objects.filter(state='3')


class ClickYesTpView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список пользователей, которые нажали "да" в чате и отписали в техподдержку
    """
    template_name = 'TgAdmin/click_yes_tp_users.html'
    model = Users
    paginate_by = 10

    def get_queryset(self):
        return Users.objects.filter(state='4')


class IsVneView(LoginRequiredMixin, ObjectListMixin, ListView):
    """
        Список пользователей, которые написали в техподдержку из-вне группы
    """
    template_name = 'TgAdmin/isvne_users.html'
    model = Users
    paginate_by = 10

    def get_queryset(self):
        return Users.objects.filter(state='5')


class UpdateText(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
        Обновление текста в групповом чате при вступлении пользователя
    """
    model = Data
    template_name = 'TgAdmin/text_create.html'
    form_class = forms.TextForm
    success_message = 'Текст/изображение для приветствия новых пользователей успешно изменен'

    def get_object(self, queryset=None):
        return Data.get_solo()

    def get_success_url(self):
        return reverse('text_create')


class UpdateBtnYes(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
        Обновление кнопки согласия
    """
    model = Data
    template_name = 'TgAdmin/btn1_create.html'
    form_class = forms.BtnYes
    success_message = 'Клавиатура "согласен" успешно изменена'

    def get_object(self, queryset=None):
        return Data.get_solo()

    def get_success_url(self):
        return reverse('btn1_create')


class UpdateBtnNo(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
        Обновление кнопки отклонения
    """
    model = Data
    template_name = 'TgAdmin/btn2_create.html'
    form_class = forms.BtnNo
    success_message = 'Клавиатура "отклонить" успешно изменена'

    def get_object(self, queryset=None):
        return Data.get_solo()

    def get_success_url(self):
        return reverse('btn2_create')


class UpdateFaq(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
        Обновление FAQ для техподдержки
    """
    model = Data
    template_name = 'TgAdmin/edit_faq.html'
    form_class = forms.FaqForm
    success_message = 'Текст для FAQ успешно изменен'

    def get_object(self, queryset=None):
        return Data.get_solo()

    def get_success_url(self):
        return reverse('edit_faq')


class UpdateIdAdmin(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
    Обновление IdAdmin для добавления в чаты
    """
    model = Data
    template_name = 'TgAdmin/edit_id_admin.html'
    form_class = forms.IdAdminForm
    success_message = 'Id пользователя успешно изменен'
    
    def get_object(self, queryset=None):
        return Data.get_solo()

    def get_success_url(self):
        return reverse('edit_id_admin')


class LoginUserView(LoginView):
    template_name = 'TgAdmin/login.html'


class LogoutThenLoginView(LoginRequiredMixin, LogoutView):
    login_url = None

    @property
    def next_page(self):
        return self.login_url or settings.LOGIN_URL


class UpdateMailingView(LoginRequiredMixin, UpdateView):
    """
        Рассылка сообщений пользователям в техподдержке
    """
    model = Data
    template_name = 'TgAdmin/mailing_create.html'
    form_class = forms.MailingForm

    def get_object(self, queryset=None):
        return Data.objects.first()

    def get_success_url(self) -> str:
        return reverse('mailing')

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        bot = TeleBot(token=settings.BOT_TOKEN2)
        if request.POST['id_user']:
            if Users.objects.filter(iduser=request.POST['id_user']):
                try:
                    if request.FILES.get('image_mailing'):
                        bot.send_photo(chat_id=request.POST['id_user'], photo=request.FILES.get('image_mailing'),
                                       caption=request.POST['text_mailing'], parse_mode='HTML')
                    else:
                        bot.send_message(chat_id=request.POST['id_user'], text=request.POST['text_mailing'],
                                         parse_mode='HTML')
                    messages.success(self.request, 'Сообщение отправлено пользователю!')
                except apihelper.ApiException:
                    messages.error(self.request, 'Пользователь остановил бота')
            else:
                messages.error(self.request, 'Данного пользователя нет в вашей базе')
        else:
            users = Users.objects.filter(Q(state='4') & Q(is_banned=False)).order_by('iduser').distinct('iduser')
            print(request.FILES.get('image_mailing'))
            if request.FILES.get('image_mailing'):
                first_send = True
                # photo = bot.send_photo(chat_id='258119893', photo=request.FILES.get('image_mailing'))
                # print(photo.json['photo'][0]['file_id'])
                for user in users:
                    try:
                        if first_send:
                            photo = bot.send_photo(chat_id=user.iduser, photo=request.FILES.get('image_mailing'))
                            photo_file_id = photo.json['photo'][0]['file_id']
                            first_send = False
                        else:
                            bot.send_photo(chat_id=user.iduser, photo=photo_file_id,
                                           caption=request.POST['text_mailing'], parse_mode='HTML')
                    except apihelper.ApiException as e:
                        bot.send_message(chat_id="258119893", text=f"{e}")
                        users = Users.objects.filter(iduser=user.iduser, state='4')
                        for usr in users:
                            usr.is_banned = True
                            usr.save(update_fields=['is_banned'])
            else:
                for user in users:
                    try:
                        bot.send_message(chat_id=user.iduser, text=request.POST['text_mailing'], parse_mode='HTML')
                    except apihelper.ApiException:
                        users = Users.objects.filter(iduser=user.iduser, state='4')
                        for usr in users:
                            usr.is_banned = True
                            usr.save(update_fields=['is_banned'])
            messages.success(self.request, 'Рассылка пользователям успешно выполнена')

            # users = Users.objects.filter(iduser=user.iduser, state='4')
            # for usr in users:
            #     usr.is_banned = True
            #     usr.save(update_fields=['is_banned'])

TgAdmin/templates/base_TgAdmin.html
{% extends 'adminlte/base.html' %}

{% block title %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-purple"><i class="fa fa-users"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'home' %}">Все</a></span>
                <span class="info-box-number">{{ all_count }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-blue"><i class="fa fa-hourglass-end"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'inaction_users' %}">Бездействие</a></span>
                <span class="info-box-number">{{ count_inaction }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-star-half-full"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'click_yes_users' %}">Нажал "согласен"</a></span>
                <span class="info-box-number">{{ count_click_yes }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-remove"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'click_no_users' %}">Нажал "Не согласен"</a></span>
                <span class="info-box-number">{{ count_click_no }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-star"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'click_yes_tp_users' %}">Нажал "Согласен" и отписал в ТП</a></span>
                <span class="info-box-number">{{ count_click_yes_tp }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-orange"><i class="fa fa-user-secret"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="{% url 'anonymous_users' %}">Попал в ТП из-вне</a></span>
                <span class="info-box-number">{{ count_tp_is_vne }}</span>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-black"><i class="fa fa-expeditedssl"></i></span>
            <div class="info-box-content">
                <span class="info-box-text"><a href="#">Заблокировали бота</a></span>
                <span class="info-box-number">{{ count_is_banned }}</span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">{% block title_table %}{% endblock %}</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                        <i class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="box-body">
                <div class="pull-left">
                    <div class="has-feedback">
                        <form action="{% url 'search_result' %}" method="get">
                            <input id="search_here" name="q" type="search" class="form-control input-sm" placeholder="Поиск...">
                            <span class="glyphicon glyphicon-search form-control-feedback"></span>
                        </form>
                    </div>
                </div>
                <div class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                    <div class="col-sm-12">
                        <table id="example" class="table table-bordered table-hover dataTable" role="grid">
                            <thead>
                            <tr role="grid">
                                <th>ID пользователя</th>
                                <th>Username</th>
                                <th>Полное имя</th>
                                <th>Дата вступления</th>
                                <th>Чат</th>
                                <th>Статус</th>
                            </tr>
                            </thead>
                            <tbody id="box_test">
                            {% for usr in object_list %}
                            <tr>
                                <td>{{ usr.iduser }}</td>
                                {% if usr.username %}
                                    <td>{{ usr.username }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
                                {% if usr.fullname %}
                                    <td>{{ usr.fullname }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
                                <td>{{ usr.date_joined }}</td>
                                {% if usr.chat_id %}
                                    <td>{{ usr.chat_id.name }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
                                <td>{{ usr.get_state_display }}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                    {% include 'TgAdmin/includes/pagination.html' %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}